Increase support to 10 type arguments for generic classes
schultek/type_plus pull request #2
Opened 2023-10-04 16:40 UTC by dagyu

TypePlus currently support a generic class with at most 5 arguments.
https://github.com/schultek/type_plus/blob/c4a542b5f79e312ceb9f747a3dbfd2b565b40d26/lib/src/unresolved_type.dart#L4-L16

In our codebase we have a class with 7 generics that we want to encode using `dart_mappable`, but we currently can't encode it without applying a patch to the `UnresolvedType` factory.

We would appreciate it if you could consider supporting up to 10 type arguments as the PR does.

2023-10-04 21:30 UTC, schultek commented
I have waited for this day to come. 😁👀

2023-10-04 21:32 UTC, schultek commented
There are other places that need to be updated too. Mainly TypeSwitcher.

2023-10-05 11:07 UTC, dagyu commented
> There are other places that need to be updated too. Mainly TypeSwitcher.

Yes, I saw, in that case you will wait for the next person who needs it 😄. Although I think a function with more than 5 type arguments is less likely than a class.

In the meantime, could you please integrate this change?

2023-10-05 14:29 UTC, dagyu commented
In #6853480e3ef0847bcb8ffa2c6f9a0798da45243e I also updated `TypeSwitcher`

2023-10-06 14:04 UTC, schultek requested changes

2023-10-06 14:04 UTC, schultek commented on lib/src/unresolved_type.dart
> +      _ => throw Exception('TypePlus only supports generic classes with up to 10 type arguments.'),
Nitpick, but "up to 10" would include 10. So either implement also the 10 arguments case or change to 9. Same for TypeSwitcher

2023-10-06 16:30 UTC, schultek commented
I will merge and add the 10 case. Thanks for the contribution.

2023-10-06 16:30 UTC, merged

2023-10-09 09:17 UTC, dagyu commented
> I will merge and add the 10 case. Thanks for the contribution.

Thanks